Add missing variable when an exception happened during stage1
    self.run()
  File "/home/user/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/fungen-AI-Powered-Funscript-Generator/application/logic/app_stage_processor.py", line 884, in _run_full_analysis_thread_target
    if stage1_success and stage2_success and (selected_mode == TrackerMode.OFFLINE_2_STAGE or stage3_success):
UnboundLocalError: local variable 'stage2_success' referenced before assignment